name: hashcode
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  cloud_firestore: ^4.4.5
  flutter_spinkit: ^5.1.0
  flutter_map: ^0.13.0
  geolocator: ^9.0.2
  map_launcher: ^2.1.1
  flutter_svg: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  image: assets/images/logo.png
  color: "#E0E0E0"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
